CREATE DATABASE DarkforgeDB
GO

USE DarkforgeDB
GO

CREATE SCHEMA Models
GO

CREATE TABLE Models.PLT(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityData VARBINARY(512) NOT NULL,
)
GO

CREATE TABLE Models.PGA(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityData VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE Models.RPF(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
PGAID INT FOREIGN KEY REFERENCES Models.PGA(EntityID),
PLTID INT FOREIGN KEY REFERENCES Models.PLT(EntityID),
Width TINYINT NOT NULL,
Height TINYINT NOT NULL,
CLUT TINYINT NOT NULL
)
GO

CREATE TABLE Models.WL(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityData VARBINARY(MAX) NOT NULL,
SampleRate SMALLINT NOT NULL,
BlockCountPerChannel INT NOT NULL,
ChannelCount TINYINT NOT NULL,
ThresholdBits TINYINT NOT NULL
)
GO


CREATE TABLE Models.FKR(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
TargetFPS TINYINT,
)
GO

CREATE TABLE Models.BN(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
FKRID INT FOREIGN KEY REFERENCES Models.FKR(EntityID),
Parent INT FOREIGN KEY REFERENCES Models.BN(EntityID),
EntityData BINARY(40) NOT NULL
)
GO


CREATE TABLE Models.ANM(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
FKRID INT FOREIGN KEY REFERENCES Models.FKR(EntityID),
)
GO

Create TABLE Models.TK(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
ANMID INT FOREIGN KEY REFERENCES Models.ANM(EntityID),
BNID INT FOREIGN KEY REFERENCES Models.BN(EntityID),
EntityData VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE Models.MDL(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
TargetTextureWidth TINYINT,
TargetTextureHeight TINYINT,
)
GO



CREATE TABLE Models.VT(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityData VARBINARY(MAX) NOT NULL,
)
GO

CREATE TABLE Models.IND(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityData VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE Models.UV(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityData VARBINARY(MAX) NOT NULL,
)
GO

CREATE TABLE Models.NRM(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityData VARBINARY(MAX) NOT NULL,
)
GO



CREATE TABLE Models.MSH(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
MDLID INT FOREIGN KEY REFERENCES Models.MDL(EntityID),
VTID INT FOREIGN KEY REFERENCES Models.VT(EntityID),
INDID INT FOREIGN KEY REFERENCES Models.IND(EntityID),
UVID INT FOREIGN KEY REFERENCES Models.UV(EntityID),
NRMID INT FOREIGN KEY REFERENCES Models.NRM(EntityID),
BNID INT FOREIGN KEY REFERENCES Models.BN(EntityID),
)
GO



CREATE TABLE Models.AST(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
MDLID INT FOREIGN KEY REFERENCES Models.MDL(EntityID),
FKRID INT FOREIGN KEY REFERENCES Models.FKR(EntityID),
PrecisionBits TINYINT NOT NULL
)
GO


CREATE SCHEMA Files
GO

CREATE TABLE Files.BMP(
EntityID VARCHAR(44) NOT NULL,
EntityData VARBINARY(MAX) NOT NULL,
)
GO

CREATE TABLE Files.WAV(
EntityID VARCHAR(44) NOT NULL,
EntityData VARBINARY(MAX) NOT NULL,
)
GO

CREATE TABLE Files.GLB(
EntityID VARCHAR(44) NOT NULL,
EntityData VARBINARY(MAX) NOT NULL,
)
GO
