CREATE DATABASE DarkforgeDB
GO

USE DarkforgeDB
GO

CREATE SCHEMA Models
GO

CREATE TABLE Models.PLT(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
EntityData VARBINARY(512) NOT NULL,
)
GO

CREATE TABLE Models.PGA(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
EntityData VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE Models.RPF(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
PGAID INT FOREIGN KEY REFERENCES Models.PGA(EntityID),
PLTID INT FOREIGN KEY REFERENCES Models.PLT(EntityID),
Width TINYINT NOT NULL,
Height TINYINT NOT NULL,
CLUT TINYINT NOT NULL
)
GO


CREATE TABLE Models.WL(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
EntityData VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE Models.VT(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
EntityData VARBINARY(MAX) NOT NULL,
ShiftBits TINYINT NOT NULL
)
GO

CREATE TABLE Models.IND(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
EntityData VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE Models.UV(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
EntityData VARBINARY(MAX) NOT NULL,
Width TINYINT NOT NULL,
Height TINYINT NOT NULL
)
GO

CREATE TABLE Models.NRM(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
EntityData VARBINARY(MAX) NOT NULL,
ShiftBits TINYINT NOT NULL
)
GO

CREATE TABLE Models.FKR(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
RigRoot TINYINT NOT NULL,
ShiftBits TINYINT NOT NULL
)
GO


CREATE TABLE Models.BN(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
FKRID INT FOREIGN KEY REFERENCES Models.FKR(EntityID),
EntityData BINARY(40) NOT NULL
)
GO

CREATE TABLE Models.ANM(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
FKRID INT FOREIGN KEY REFERENCES Models.FKR(EntityID),
ShiftBits TINYINT NOT NULL
)
GO

Create TABLE Models.TK(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
ANMID INT FOREIGN KEY REFERENCES Models.ANM(EntityID),
BNID INT FOREIGN KEY REFERENCES Models.BN(EntityID),
EntityData VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE Models.MDL(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
TextureID INT FOREIGN KEY REFERENCES Models.RPF(EntityID),
FKRID INT FOREIGN KEY REFERENCES Models.FKR(EntityID)
)
GO

CREATE TABLE Models.MSH(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityOrder INT NOT NULL,
MDL INT FOREIGN KEY REFERENCES Models.MDL(EntityID),
VTID INT FOREIGN KEY REFERENCES Models.VT(EntityID),
UVID INT FOREIGN KEY REFERENCES Models.UV(EntityID),
NRMID INT FOREIGN KEY REFERENCES Models.NRM(EntityID),
BNID INT FOREIGN KEY REFERENCES Models.BN(EntityID),
)
GO


CREATE SCHEMA Files
GO

CREATE TABLE Files.BMP(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityHash VARCHAR(255) NOT NULL,
EntityData VARBINARY(MAX) NOT NULL,
)
GO

CREATE TABLE Files.WAV(
EntityID INT IDENTITY(1,1) PRIMARY KEY,
EntityHash VARCHAR(255) NOT NULL,
EntityData VARBINARY(MAX) NOT NULL,
)
GO

